base_lr: 0.1
batch_size: 96
config: ./config/kinetics-skeleton/train_joint.yaml
device:
- 0
- 1
- 2
- 3
eval_interval: 5
feeder: feeders.feeder.Feeder
ignore_weights: []
log_interval: 100
model: model.agcn3.Model
model_args:
  graph: graph.kinetics.Graph
  graph_args:
    labeling_mode: spatial
  num_class: 5
  num_person: 2
  num_point: 17
model_saved_name: ./runs/ki_agcn_joint_SrchCT
nesterov: true
num_epoch: 80
num_worker: 32
only_train_epoch: 0
only_train_part: false
optimizer: SGD
phase: train
print_log: true
save_interval: 2
save_score: false
seed: 1
show_topk:
- 1
- 2
start_epoch: 0
step:
- 45
- 60
- 75
test_batch_size: 48
test_feeder_args:
  data_path: ./data/kinetics/val_data_joint.npy
  label_path: ./data/kinetics/val_label.pkl
train_feeder_args:
  data_path: ./data/kinetics/train_data_joint.npy
  debug: false
  label_path: ./data/kinetics/train_label.pkl
  random_choose: true
  random_move: true
  window_size: 150
warm_up_epoch: 0
weight_decay: 0.0001
weights: ''
work_dir: ./work_dir/kinetics/agcn_joint_SrchCT
